site_name: Firereact
site_url: https://firereact.erayerdin.com
repo_url: https://github.com/erayerdin/firereact

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - toc.follow
    - toc.integrate
    - navigation.top
  palette: 
    # Palette toggle for light mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: orange
      accent: deep purple
      toggle:
        icon: material/brightness-4 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: orange
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

nav:
  - Firestore:
    - firestore/reading-a-single-document.md
    - firestore/listing-a-collection.md
    - firestore/creating-documents.md
    - firestore/updating-documents.md
    - firestore/deleting-documents.md
  - Hooks:
    - Firestore:
      - hooks/useDocument-hook.md
      - hooks/useCollection-hook.md
      - hooks/useAddDocument-hook.md
      - hooks/useSetDocument-hook.md
      - hooks/useDeleteDocument-hook.md
  - Components:
    - Firestore:
      - components/FirestoreDocument.md

plugins:
  - privacy
  - social
  - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes