name: "Check"
on: pull_request

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        run: npm i
      - name: "Run Firebase Emulators"
        run: npm run firebase:emulators &
      - name: "Wait for Firebase Emulators"
        run: sleep 10
      - name: "Test"
        run: npm run test
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        run: npm i
      - name: "Check Linting"
        run: npm run lint:check
  formatter:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install dependencies"
        run: npm i
      - name: "Check Formatting"
        run: npm run formatter:check