name: "Check"
on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Create Gcloud Auth Key"
        env:
          FIREACT_GCLOUD_KEY: ${{ secrets.FIREACT_GCLOUD_SECRET_KEY_CONTENT }}
        run: echo $FIREACT_GCLOUD_KEY > $HOME/gcloud.json
      - name: "Install dependencies"
        run: npm i
      - name: "Download Firebase Emulators"
        run: npm run firebase:emulators:download
      - name: "Run Firebase Emulators"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/gloud.json
        uses: JarvusInnovations/background-action@v1
        with:
          run: npm run firebase:emulators:run
          wait-on: |
            http://127.0.0.1:5001
            http://127.0.0.1:8080
            http://127.0.0.1:9099
          wait-for: 3m
      - name: "Wait for Firebase Emulators"
        run: sleep 10
      - name: "Test"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: npm run test
      - name: "Analyze Coverage"
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 3
          max_attempts: 3
          command: npm run test:coverage
      - name: "Upload Coverage"
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: npm i
      - name: "Check Linting"
        run: npm run lint:check
  formatter:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Install dependencies"
        run: npm i
      - name: "Check Formatting"
        run: npm run formatter:check
