name: "Test"
on: pull_request

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Run Firebase Emulators"
        run: npm run firebase:emulators &
      - name: "Wait for Firebase Emulators"
        run: sleep 10
      - name: "Install dependencies"
        run: npm i
      - name: "Test"
        run: npm run test